name: Build i686 musl

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y musl-tools gcc-multilib

    - name: Build project
      run: |
        make CC=i686-linux-musl-gcc
